module.exports = {
  defaultJson() {
    return {
      termType: '',
      priceDescription: '',
      pricePerUnit: 0,
      leaseContractLength: '',
      purchaseOption: 'No Upfront',
      offeringClass: 'Standard',
      productFamily: '',
      location: '',
      instanceType: '',
      currentGeneration: '',
      instanceFamily: '',
      vCPU: 0,
      vCpuID: 0,
      memory: '',
      ramID: 0,
      storage: '',
      storageID: 0,
      diskPrice: 0,
      networkPerformance: '',
      tenancy: '',
      operatingSystem: '',
      operatingSystemPrice: false,
      preInstaledSoftware: null,
      licenseModel: '',
    };
  },

  newJson(e) {
    return {
      termType: e.termType,
      priceDescription: e.priceDescription,
      pricePerUnit: e.pricePerUnit,
      leaseContractLength: e.leaseContractLength,
      purchaseOption: e.purchaseOption,
      offeringClass: e.offeringClass,
      productFamily: e.productFamily,
      location: e.location,
      instanceType: e.instanceType,
      currentGeneration: e.currentGeneration,
      instanceFamily: e.instanceFamily,
      vCPU: e.vCPU,
      vCpuID: e.vCpuID,
      memory: e.memory,
      ramID: e.ramID,
      storage: e.storage,
      storageID: e.storageID,
      diskPrice: e.diskPrice,
      networkPerformance: e.networkPerformance,
      tenancy: e.tenancy,
      operatingSystem: e.operatingSystem,
      operatingSystemPrice: e.operatingSystemPrice,
      preInstaledSoftware: e.preInstaledSoftware,
      licenseModel: e.licenseModel,
    };
  },
};
