module.exports = {
  //Método para retonar schema do json padrão com as informações dos bancos de dados
  defaultJson() {
    return {
      termType: '',
      priceDescription: '',
      pricePerUnit: 0,
      leaseContractLength: '',
      purchaseOption: 'No Upfront',
      offeringClass: 'Standard',
      productFamily: '',
      location: '',
      instanceType: '',
      currentGeneration: '',
      instanceFamily: '',
      vCPU: 0,
      vCpuID: 0,
      memory: '',
      ramID: 0,
      storage: '',
      storageID: 0,
      diskPrice: 0,
      networkPerformance: '',
      tenancy: '',
      operatingSystem: '',
      operatingSystemPrice: false,
      preInstaledSoftware: null,
      licenseModel: '',
    };
  },

  //Método responsável por criar um novo objeto json com as informações correntes
  newJson(e) {
    return {
      termType: e.termType,
      priceDescription: e.priceDescription,
      pricePerUnit: e.pricePerUnit,
      leaseContractLength: e.leaseContractLength,
      purchaseOption: e.purchaseOption,
      offeringClass: e.offeringClass,
      productFamily: e.productFamily,
      location: e.location,
      instanceType: e.instanceType,
      currentGeneration: e.currentGeneration,
      instanceFamily: e.instanceFamily,
      vCPU: e.vCPU,
      vCpuID: e.vCpuID,
      memory: e.memory,
      ramID: e.ramID,
      storage: e.storage,
      storageID: e.storageID,
      diskPrice: e.diskPrice,
      networkPerformance: e.networkPerformance,
      tenancy: e.tenancy,
      operatingSystem: e.operatingSystem,
      operatingSystemPrice: e.operatingSystemPrice,
      preInstaledSoftware: e.preInstaledSoftware,
      licenseModel: e.licenseModel,
    };
  },

  //Método responsável por retornar todas as localizações onde podemos provisionar uma vsi
  getLocations() {
    return [
      { groupId: 503, name: 'Montreal 1', code: 'mon01' },
      { groupId: 503, name: 'Montreal 2', code: 'mon02' },
      { groupId: 503, name: 'Toronto 1', code: 'tor01' },
      { groupId: 503, name: 'Toronto 2', code: 'tor02' },
      { groupId: 503, name: 'Amsterdam 2', code: 'ams02' },
      { groupId: 503, name: 'Amsterdam 1', code: 'ams01' },
      { groupId: 503, name: 'Amsterdam 3', code: 'ams03' },
      { groupId: 505, name: 'London 2', code: 'lon02' },
      { groupId: 505, name: 'London 5', code: 'lon05' },
      { groupId: 505, name: 'London 1', code: 'lon01' },
      { groupId: 505, name: 'London 6', code: 'lon06' },
      { groupId: 505, name: 'Stockholm 01', code: 'sto01' },
      { groupId: 505, name: 'London 4', code: 'lon04' },
      { groupId: 505, name: 'Oslo 2', code: 'osl02' },
      { groupId: 505, name: 'Mexico 1', code: 'mex01' },
      { groupId: 505, name: 'London 3', code: 'lon03' },
      { groupId: 505, name: 'Oslo 1', code: 'osl01' },
      { groupId: 507, name: 'Paris 2', code: 'par02' },
      { groupId: 507, name: 'Seoul 1', code: 'seo01' },
      { groupId: 507, name: 'Paris 6', code: 'par06' },
      { groupId: 507, name: 'Frankfurt 2', code: 'fra02' },
      { groupId: 507, name: 'Seoul 2', code: 'seo02' },
      { groupId: 507, name: 'Frankfurt 1', code: 'fra01' },
      { groupId: 507, name: 'Milan 1', code: 'mil01' },
      { groupId: 507, name: 'Milan 2', code: 'mil02' },
      { groupId: 507, name: 'Frankfurt 5', code: 'fra05' },
      { groupId: 507, name: 'Paris 4', code: 'par04' },
      { groupId: 507, name: 'Paris 1', code: 'par01' },
      { groupId: 507, name: 'Frankfurt 3', code: 'fra03' },
      { groupId: 507, name: 'Frankfurt 4', code: 'fra04' },
      { groupId: 507, name: 'Paris 5', code: 'par05' },
      { groupId: 509, name: 'Tokyo 1', code: 'tok01' },
      { groupId: 509, name: 'Hong Kong 2', code: 'hkg02' },
      { groupId: 509, name: 'Tokyo 2', code: 'tok02' },
      { groupId: 509, name: 'Tokyo 5', code: 'tok05' },
      { groupId: 509, name: 'Osaka 21', code: 'osa21' },
      { groupId: 509, name: 'Tokyo 3', code: 'tok03' },
      { groupId: 509, name: 'Singapore 2', code: 'sng02' },
      { groupId: 509, name: 'Tokyo 4', code: 'tok04' },
      { groupId: 509, name: 'Hong Kong 3', code: 'hkg03' },
      { groupId: 509, name: 'Osaka 23', code: 'osa23' },
      { groupId: 509, name: 'Hong Kong 1', code: 'hkg01' },
      { groupId: 509, name: 'Singapore 1', code: 'sng01' },
      { groupId: 509, name: 'Osaka 1', code: 'osa01' },
      { groupId: 509, name: 'Osaka 22', code: 'osa22' },
      { groupId: 545, name: 'Sydney 2', code: 'syd02' },
      { groupId: 545, name: 'Sydney 3', code: 'syd03' },
      { groupId: 545, name: 'Sydney 1', code: 'syd01' },
      { groupId: 545, name: 'Chennai 1', code: 'che01' },
      { groupId: 545, name: 'Sydney 4', code: 'syd04' },
      { groupId: 545, name: 'Melbourne 2', code: 'mel02' },
      { groupId: 545, name: 'Melbourne 1', code: 'mel01' },
      { groupId: 545, name: 'Sao Paulo 02', code: 'sao02' },
      { groupId: 545, name: 'Sao Paulo 1', code: 'sao01' },
      { groupId: 545, name: 'Sydney 5', code: 'syd05' },
      { groupId: null, name: 'Dallas 5', code: 'dal05' },
      { groupId: null, name: 'Dallas 6', code: 'dal06' },
      { groupId: null, name: 'Dallas 9', code: 'dal09' },
      { groupId: null, name: 'Dallas 10', code: 'dal10' },
      { groupId: null, name: 'Dallas 12', code: 'dal12' },
      { groupId: null, name: 'Dallas 13', code: 'dal13' },
      { groupId: null, name: 'Houston 2', code: 'hou02' },
      { groupId: null, name: 'San Jose 1', code: 'sjc01' },
      { groupId: null, name: 'San Jose 3', code: 'sjc03' },
      { groupId: null, name: 'San Jose 4', code: 'sjc04' },
      { groupId: null, name: 'Washington 1', code: 'wdc01' },
      { groupId: null, name: 'Washington 4', code: 'wdc04' },
      { groupId: null, name: 'Washington 5', code: 'wdc06' },
      { groupId: null, name: 'Washington 7', code: 'wdc07' },
    ];
  },
};

/*
{ groupId: null, name: 'Dallas 5', code: 'dal05' },
  { groupId: null, name: 'Dallas 6', code: 'dal06' },
  { groupId: null, name: 'Dallas 9', code: 'dal09' },
  { groupId: null, name: 'Dallas 10', code: 'dal10' },
  { groupId: null, name: 'Dallas 12', code: 'dal12' },
  { groupId: null, name: 'Dallas 13', code: 'dal13' },
  { groupId: null, name: 'Houston 2', code: 'hou02' },
  { groupId: null, name: 'San Jose 1', code: 'sjc01' },
  { groupId: null, name: 'San Jose 3', code: 'sjc03' },
  { groupId: null, name: 'San Jose 4', code: 'sjc04' },
  { groupId: null, name: 'Washington 1', code: 'wdc01' },
  { groupId: null, name: 'Washington 4', code: 'wdc04' },
  { groupId: null, name: 'Washington 5', code: 'wdc06' },
  { groupId: null, name: 'Washington 7', code: 'wdc07' },
*/
